version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_fashion_store
    restart: always
    environment:
      MYSQL_DATABASE: fashion_store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
